# Generated by Django 4.1.6 on 2023-03-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telefon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phones",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="telefon.brand",
            ),
        ),
    ]
