# Generated by Django 4.1.6 on 2023-03-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telefon", "0002_alter_phones_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="phones",
            name="color",
            field=models.CharField(default="black", max_length=20, verbose_name="Цвет"),
        ),
    ]
